### ISSUE TITLE
[FEATURE] Color constructor with floats should have range 0 to 1

### ISSUE THREAD

**Issue by nt314p** [OrbitalEngine/Orbital#17]
**Is your feature request related to a problem? Please describe.**
Usually when floats are used to represent colors, the color value ranges from 0 to 1, not 0 to 255.

**Describe the solution you'd like**
The color constructor which takes floats should assume the floats range from 0 to 1. To convert from these floats to the 0 to 255 byte values, simply multiply the float components by 255.9999 and then cast.

**Comment by Yeffian** [comment]
So basically, take the floats in from a range  of 0 to 1, and convert to the standard 255 in bytes? I'll get to work on it after I get home, thanks for opening an issue!
