### ISSUE TITLE
[FEATURE] Move `.getRaylibColor()` function to `RaylibUtil` class 

### ISSUE THREAD

**Issue by Yeffian** [OrbitalEngine/Orbital#19]
**Is your feature request related to a problem? Please describe.**
Currently, the `.getRaylibColor()` function is on the `Color` object itself, instead of in the `RaylibUtil` class, which is meant for converting between Raylib and Orbital classes.

**Describe the solution you'd like**
Move the `.getRaylibColor()` function to the appropriate class, and update all uses of it.

**Comment by andreaevolo** [comment]
Can I be assigned to this issue?

**Comment by divyansh-ag-03** [comment]
Hi @YeffyCodeGit I am well versed with Java and Python, and I am looking forward to solving the different issues this Hacktoberfest. I will be happy to work on it. Please assign the issue to me.

**Comment by DevPJ9** [comment]
Hi @YeffyCodeGit i would like to work on this issue can you assign that to me ? :)

**Comment by Yeffian** [comment]
@divyansh-ag-03 @DevPJ9 Sorry, but @andreaevolo has already started to work on this issue, and I've already assigned him. Maybe you guys could look at some of the other issues? Thanks for wanting to contribute!

**Comment by Yeffian** [comment]
Closed by #21
