### ISSUE TITLE
[FEATURE] Implement Google Code Format in Spotless

### ISSUE THREAD

**Issue by Yeffian** [OrbitalEngine/Orbital#20]
**Is your feature request related to a problem? Please describe.**
Even though we have the Spotless code formatter implemented, we still aren't actually using a code format throughout the project. 

**Describe the solution you'd like**
Use the Google Java Format in Spotless and set it up properly.

**Describe alternatives you've considered**
After looking through the Google Java Format, I like it, but if anyone thinks there are any other formats that suit better to the style of this project, feel free to discuss in this issue!

**Comment by c99SRS** [comment]
HI @YeffyCodeGit please assign this to me. I can work on it.

**Comment by Yeffian** [comment]
#25 closes
